### ISSUE TITLE
Template?

### ISSUE THREAD

**Issue by nojaf** [jgrund/fable-jest#6]
I didn't find one but I guess it would be nice if there is a dotnet cli template for this.

**Comment by jgrund** [comment]
Hey @nojaf,

I've created a template repo [here](https://github.com/jgrund/fable-template-jest)

Detailed instructions on setup / install can be found [here](https://github.com/jgrund/fable-template-jest/blob/master/Content/README.md)

The template can be installed and run the usual way with:

`dotnet new -i Fable.Template.Jest`

and

`dotnet new fable-jest`

**Comment by nojaf** [comment]
Thanks a lot for this!
